name: iyuque
description: 一个好用的语雀手机客户端

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.0
  cupertino_icons: ^1.0.2
  dio: 4.0.0
  cookie_jar: 1.0.1
  # json注解 #https://pub.dartlang.org/packages/json_serializable
  json_annotation: ^3.0.1
  #图标字体的一个库 https://pub.dartlang.org/packages/font_awesome_flutter
  font_awesome_flutter: 9.1.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.3.0
  #用于从Android和iOS图像库中选择图像，并使用相机拍摄新照片 https://pub.dartlang.org/packages/image_picker
  image_picker: ^0.8.3
  #图片压缩格式转换 https://github.com/brendan-duncan/image
  image: ^3.0.2
  #大图浏览组件
  photo_view: ^0.12.0
  #最好用的路由导航框架 https://pub.dartlang.org/packages/fluro
  fluro: ^1.7.8
  #图片压缩 https://pub.dartlang.org/packages/flutter_image_compress
  flutter_image_compress: ^0.7.0
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 2.0.1
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.9
  # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  fluintl: ^0.1.3
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.0.9
  pull_to_refresh: ^2.0.0
  # webview_flutter
  webview_flutter: 2.0.12
  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.24.1
  # https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.2.0+1
  # https://github.com/flutterchina/flukit.
  flukit: ^1.0.2
  html: ^0.15.0
  device_info: ^2.0.2
  permission_handler: ^7.1.0
  # 桌面图标提醒
  flutter_app_badger: ^1.2.0
  #获取app信息
  package_info: ^2.0.2
  #更新插件
  ota_update: ^3.0.2
  #加密包
  crypto: ^3.0.1
  flutter_quill: ^1.9.5
  #sqlite支持
  html_editor_enhanced: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.2


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/avatar.png
    - assets/images/ic_launcher.png
    - assets/images/ic_data_empty.png
    - assets/images/ic_network_error.png
    - assets/images/splash_bg.png
